var movies = [
  {
    "notes": "",
    "doi": "n.a.",
    "isbn": "n.a.",
    "idioma": "EN",
    "img": "database/assets/img/content/cszambia.png",
    "free_access": "Yes",
    "europe_related": "G",
    "abstract": "This Case study presents the status of Conservation Agriculture in Zambia. It is one In a series of eight case studies about conservation Agriculture in Africa.",
    "read_more": "Visible",
    "more": "",
    "content": "http://catoolbox.act-africa.org/wp-content/uploads/2014/12/Zambia_casestudy.pdf",
    "reference": "Conservation Agriculture in Zambia: A case study of Southern Province",
    "category": "Case Study",
    "sub_topic": "",
    "main_topic": "EQUIPMENT",
    "id": 1
  },
  {
    "notes": "",
    "doi": "n.a.",
    "isbn": "n.a.",
    "idioma": "EN",
    "img": "database/assets/img/content/csuganda.png",
    "free_access": "Yes",
    "europe_related": "G",
    "abstract": "Conservation Agriculture : A Uganda Case Study: This Case study presents the status of Conservation Agriculture in Uganda. It is one In a series of eight case studies about conservation Agriculture in Africa. ",
    "read_more": "Visible",
    "more": "",
    "content": "http://catoolbox.act-africa.org/wp-content/uploads/2014/12/Uganda_casestudy.pdf",
    "reference": "Conservation Agriculture : A Uganda Case Study",
    "category": "Case Study",
    "sub_topic": "RESIDUE MANAGEMENT",
    "main_topic": "MANAGEMENT TECHNIQUES",
    "id": 2
  },
    {
    "notes": "",
    "doi": "n.a.",
    "isbn": "n.a.",
    "idioma": "EN",
    "img": "database/assets/img/content/cszambia.png",
    "free_access": "Yes",
    "europe_related": "G",
    "abstract": "This Case study presents the status of Conservation Agriculture in Zambia. It is one In a series of eight case studies about conservation Agriculture in Africa.",
    "read_more": "Visible",
    "more": "",
    "content": "http://catoolbox.act-africa.org/wp-content/uploads/2014/12/Zambia_casestudy.pdf",
    "reference": "Conservation Agriculture in Zambia: A case study of Southern Province",
    "category": "Case Study",
    "sub_topic": "",
    "main_topic": "EQUIPMENT",
    "id": 3
  },
    {
    "notes": "",
    "doi": "n.a.",
    "isbn": "n.a.",
    "idioma": "EN",
    "img": "database/assets/img/content/cszambia.png",
    "free_access": "Yes",
    "europe_related": "G",
    "abstract": "This Case study presents the status of Conservation Agriculture in Zambia. It is one In a series of eight case studies about conservation Agriculture in Africa.",
    "read_more": "Visible",
    "more": "",
    "content": "http://catoolbox.act-africa.org/wp-content/uploads/2014/12/Zambia_casestudy.pdf",
    "reference": "Conservation Agriculture in Zambia: A case study of Southern Province",
    "category": "Case Study",
    "sub_topic": "",
    "main_topic": "EQUIPMENT",
    "id": 4
  },
    {
    "notes": "",
    "doi": "n.a.",
    "isbn": "n.a.",
    "idioma": "EN",
    "img": "database/assets/img/content/cszambia.png",
    "free_access": "Yes",
    "europe_related": "G",
    "abstract": "This Case study presents the status of Conservation Agriculture in Zambia. It is one In a series of eight case studies about conservation Agriculture in Africa.",
    "read_more": "Visible",
    "more": "",
    "content": "http://catoolbox.act-africa.org/wp-content/uploads/2014/12/Zambia_casestudy.pdf",
    "reference": "Conservation Agriculture in Zambia: A case study of Southern Province",
    "category": "Case Study",
    "sub_topic": "",
    "main_topic": "EQUIPMENT",
    "id": 5
  },
     {
    "notes": "",
    "doi": "n.a.",
    "isbn": "n.a.",
    "idioma": "EN",
    "img": "database/assets/img/content/proceedings1.png",
    "free_access": "Yes",
    "europe_related": "G",
    "abstract": " Conservation Agriculture: Building Entrepreneurship and Resilient Farming Systems 2014",
    "read_more": "Visible",
    "more": "",
    "content": "database/assets/bookProceedings of the First Africa Congress on Conservation Agriculture.pdf",
    "reference": "Proceedings of the First Africa Congress on Conservation Agriculture",
    "category": "Books and Manuals",
    "sub_topic": "",
    "main_topic": "EQUIPMENT",
    "id": 6
  },
  {
    "notes": "",
    "doi": "n.a.",
    "isbn": "n.a.",
    "idioma": "EN",
    "img": "database/assets/img/content/bkpapers.png",
    "free_access": "Yes",
    "europe_related": "G",
    "abstract": "N.A.",
    "read_more": "NoVisible",
    "more": "",
    "content": "database/assets/Book of Condensed Papers of the First Africa Congress on Conservation Agriculture, 18 - 21 March, 2014, Lusaka. African Conservation Tillage Network.pdf",
    "reference": "Book of Condensed Papers of the First Africa Congress on Conservation Agriculture, 18 - 21 March, 2014, Lusaka. African Conservation Tillage Network",
    "category": "Books and Manuals",
    "sub_topic": "COVER CROPS",
    "main_topic": "MANAGEMENT TECHNIQUES",
    "id": 7
  }
]
